version: "2"
services:
  backend:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    container_name: producscraper
    ports:
      - "3009:3009"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/productscraper
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - /home/mongo/database:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped